Adding regression test
ROCmSoftwarePlatform/rccl pull request #1045
Opened 2024-01-15 15:14 UTC by AtlantaPepsi

Does an AllReduce of 5KB data between 2 devices under 1 process, blocks regression that makes execution time greater than 5ms.

2024-01-15 17:42 UTC, wenkaidu commented
1. need to go through all protocols.
2. need to add a few warm up cycles, then take timing measurements from average of 10-20 iterations.

2024-01-16 18:21 UTC, wenkaidu commented on test/StandaloneTests.cpp
> +      printf("sada%d\n", msElapsed);
Logs always show "0". Can you make msElapsed as microseconds and float? We would like to see some numbers which varies depends on protocol to make sure it works as expected.

2024-01-17 16:21 UTC, wenkaidu approved these changes

2024-01-17 16:55 UTC, gilbertlee-amd requested changes

2024-01-17 16:55 UTC, gilbertlee-amd commented on test/StandaloneTests.cpp
> +      EXPECT_LT(usElapsed/15.0, 5000);
iter isn't hard coded, yet this is.  Should pick one or the other.

2024-01-18 15:41 UTC, gilbertlee-amd approved these changes

2024-01-18 15:46 UTC, merged