[UT] Start supporting multiple group calls and graphs
ROCmSoftwarePlatform/rccl pull request #1151
Opened 2024-04-19 05:20 UTC by BertanDogancay

## Details
___Do not mention proprietary info or link to internal work items in this PR.___

**Work item:**  LWPCOMMLIBS-238

**What were the changes?**  
Start supporting multiple group calls and graphs for UT

**Why were the changes made?**  
Launching captured graphs in pseudorandom order, and combine with RCCL API direct launches in between graph launches.

**How was the outcome achieved?**  
Modifying UT framework so that group calls and graphs are stored to be executed on demand.

**Additional Documentation:**  
Done in a way so that other test cases don't require any additional change.

## Approval Checklist
___Do not approve until these items are satisfied.___
- [ ] Verify the CHANGELOG has been updated, if
  - there are any NCCL API version changes,
  - any changes impact library users, and/or
  - any changes impact any other ROCm library.

2024-04-19 21:09 UTC, wenkaidu approved these changes

2024-04-23 18:21 UTC, gilbertlee-amd requested changes

2024-04-23 18:21 UTC, gilbertlee-amd commented on test/common/TestBedChild.hpp
> +      CHIILD_LAUNCH_GRAPHS   = 7,  // LaunchGraphs()
CHIILD

2024-04-25 15:49 UTC, gilbertlee-amd approved these changes

2024-04-25 17:11 UTC, merged