Report error when collective is not enabled in build
ROCmSoftwarePlatform/rccl pull request #1177
Opened 2024-05-13 23:49 UTC by wenkaidu

## Details
___Do not mention proprietary info or link to internal work items in this PR.___

**Work item:** _"Internal", or link to GitHub issue (if applicable)._

**What were the changes?**  
Report error when collective is not enabled in build.

**Why were the changes made?**  
To make user aware of unsupported collectives instead of data corruption.

**How was the outcome achieved?**  
Check for invalid function index

**Additional Documentation:**  

## Approval Checklist
___Do not approve until these items are satisfied.___
- [ ] Verify the CHANGELOG has been updated, if
  - there are any NCCL API version changes,
  - any changes impact library users, and/or
  - any changes impact any other ROCm library.

2024-05-14 13:43 UTC, nusislam commented on src/enqueue.cc
> +    WARN("%s: unspported collective. Please ensure the collective has been enabled in build.", __func__);
Under what circumstances will a collective be disabled or unsupported? Can you give an example?

2024-05-14 14:37 UTC, wenkaidu commented on src/enqueue.cc
> +    WARN("%s: unspported collective. Please ensure the collective has been enabled in build.", __func__);
https://github.com/ROCm/rccl/pull/986

2024-05-15 15:23 UTC, nusislam approved these changes

2024-05-15 15:23 UTC, gilbertlee-amd requested changes

2024-05-15 15:23 UTC, gilbertlee-amd commented on src/enqueue.cc
> +    WARN("%s: unspported collective. Please ensure the collective has been enabled in build.", __func__);
typo: unsupported

2024-05-15 15:23 UTC, gilbertlee-amd commented on src/enqueue.cc
> +    WARN("%s: unspported collective. Please ensure the collective has been enabled in build.", __func__);
typo:

2024-05-15 15:26 UTC, wenkaidu commented on src/enqueue.cc
> +    WARN("%s: unspported collective. Please ensure the collective has been enabled in build.", __func__);
fixed

2024-05-15 15:29 UTC, PedramAlizadeh approved these changes

2024-05-16 17:11 UTC, merged