Adding User Buffer Registration support for Unit test
ROCmSoftwarePlatform/rccl pull request #1199
Opened 2024-06-04 16:40 UTC by AtlantaPepsi

## Details
___Do not mention proprietary info or link to internal work items in this PR.___
This is a WIP PR for integrating user registered buffer support in RCCL unit test.

**Work item:** Internal

**What were the changes?**  
 Currently on coded UBR for network send and recv in TestBed, added a SendRecv test, correctness passed with no significant performance difference. Will probably do further modifications for collectives

## Approval Checklist
___Do not approve until these items are satisfied.___
- [ ] Verify the CHANGELOG has been updated, if
  - there are any NCCL API version changes,
  - any changes impact library users, and/or
  - any changes impact any other ROCm library.

2024-07-22 21:20 UTC, corey-derochie-amd requested changes

2024-07-22 21:20 UTC, corey-derochie-amd commented on test/common/TestBedChild.cpp
> +                                userRegistered ? "user registered buffer" : "internal copy",
Where is this meant to appear in the format string?

2024-07-29 23:42 UTC, wenkaidu approved these changes

2024-07-30 00:12 UTC, corey-derochie-amd commented on test/common/TestBedChild.cpp
> +                                userRegistered ? "user registered buffer" : "internal copy",
```suggestion
        if (this->verbose) INFO("Rank %d on child %d allocates memory for collective %d in group %d on device %d (%s,%s,%s) Input: %p Output %p\n",
                                globalRank, this->childId, collIdx, groupId, this->deviceIds[localRank],
                                inPlace ? "in-place" : "out-of-place",
                                useManagedMem ? "managed" : "unmanaged",
                                userRegistered ? "user registered buffer" : "internal copy",
```

2024-07-30 05:51 UTC, corey-derochie-amd approved these changes

2024-07-30 17:39 UTC, merged