adding all nccl apis to api_support to enable rccl tracing by rocprofv3
ROCmSoftwarePlatform/rccl pull request #1297
Opened 2024-08-14 16:16 UTC by mberenjk

## Details
___Do not mention proprietary info or link to internal work items in this PR.___

**Work item:** _"Internal", or link to GitHub issue (if applicable)._

**What were the changes?**  
-  api_trace.h added that includes all nccl apis.

- api_trace.cc that includes the implementation of function table path.

CMakeList changed to add rocprofiler-register.
collective.cc, init.cc, register.cc, enqueue.cc, group.cc, msccl.cc modified to call all nccl apis through api_trace.h

**Why were the changes made?**  
This change is enable rccl tracing in rocprofv3.

**How was the outcome achieved?**  
Modifying collectives.cc and other files and running UT which works fine. rccl-tests also runs fine with the new changes. This PR eventually needs to be tested on rocprofv3.

**Additional Documentation:**  
 This PR eventually needs to be tested on rocprofv3.
 
## Approval Checklist
___Do not approve until these items are satisfied.___
- [ ] Verify the CHANGELOG has been updated, if
  - there are any NCCL API version changes,
  - any changes impact library users, and/or
  - any changes impact any other ROCm library.

2024-08-14 18:46 UTC, corey-derochie-amd commented on src/include/api_trace.h
> +ncclResult_t ncclAllGather_impl(const void* sendbuff, void* recvbuff, size_t sendcount,
Is `#ifdef __cplusplus \ extern "C" {` necessary here?

2024-08-20 18:00 UTC, jrmadsen requested changes
Also, it appears all the comments on tbe other PR weren’t addressed

2024-08-20 18:00 UTC, jrmadsen commented on CMakeLists.txt
> +    FILES ${PROJECT_BINARY_DIR}/rccl/include/rccl.h src/include/nccl_net.h src/include/api_trace.h
I’d remove these changes since the api_trace.h file doesn’t need to support the file reorg backwards compatibility.

2024-08-20 18:00 UTC, jrmadsen commented on CMakeLists.txt
> +    FILES ${PROJECT_BINARY_DIR}/include/rccl.h src/include/nccl_net.h src/include/api_trace.h
I’d remove these changes since the api_trace.h file doesn’t need to support the file reorg backwards compatibility.

2024-08-21 00:50 UTC, jrmadsen approved these changes

2024-08-22 17:36 UTC, merged

2024-09-06 17:09 UTC, jrmadsen commented
@mberenjk please open a new PR which changes the `#include "nccl.h"` in `src/include/api_trace.h` to `#include <rccl/rccl.h>`. RCCL does not install a `nccl.h` header so when we try to include this file in rocprofiler-sdk, it causes problems

CC: @MythreyaK