Increased maximum number of XML nodes to support CPX mode. (#1386)
ROCmSoftwarePlatform/rccl pull request #1396
Opened 2024-10-26 04:58 UTC by thananon

## Details
Cherry pick from #1386 to 6.3 release branch.

**Why were the changes made?**  
Original detail in PR ##1386. This is required for RCCL to run CPX mode properly in ROCm 6.3.

## Approval Checklist
___Do not approve until these items are satisfied.___
- [ ] Verify the CHANGELOG has been updated, if
  - there are any NCCL API version changes,
  - any changes impact library users, and/or
  - any changes impact any other ROCm library.

2024-10-28 21:40 UTC, corey-derochie-amd requested changes
I believe this should be merged to `release-staging/rocm-rel-6.3` instead, I need to confirm.

2024-10-28 21:40 UTC, corey-derochie-amd commented
@thananon Why did these checks fail?

2024-10-28 22:13 UTC, thananon commented
@corey-derochie-amd  the main branch seems to fail the same way before this PR. I am not sure.

2024-10-29 21:42 UTC, corey-derochie-amd approved these changes

2024-11-05 16:01 UTC, merged