Code enhancements
ROCmSoftwarePlatform/rccl pull request #1429
Opened 2024-11-22 00:37 UTC by PJAvinash

## Details
Enhancing code

**Work item:** "Internal"
**What were the changes?**  
Modifying / enhancing failure path in ncclIBInit()

**Why were the changes made?**  
Code improvements

**How was the outcome achieved?**  
Analyzing the code with debugger
**Additional Documentation:**  
pthread_detach() call is removed as it is a side effect of earlier nccl sync

## Approval Checklist
___Do not approve until these items are satisfied.___
- [ ] Verify the CHANGELOG has been updated, if
  - there are any NCCL API version changes,
  - any changes impact library users, and/or
  - any changes impact any other ROCm library.

2024-11-22 10:39 UTC, thananon approved these changes
This looks good to me.

2025-01-03 01:19 UTC, wenkaidu commented on src/transport/net_ib.cc
> -          // [/RCCL]
Why removing pthread_detach? This was added to fix a memory leak issue.

2025-01-03 16:45 UTC, PJAvinash commented on src/transport/net_ib.cc
pthread_detach() is being called twice with same parameter, first time at line 486, second call will  simply return -1 and it is not being checked, and has no effect.

2025-01-03 16:46 UTC, PJAvinash commented on src/transport/net_ib.cc
> -          // [/RCCL]
pthread_detach() is being called twice with same parameter, first time at line 486, second call will simply return -1 and it is not being checked, and has no effect.

2025-01-03 19:20 UTC, wenkaidu approved these changes

2025-02-11 17:23 UTC, corey-derochie-amd requested changes
Please provide a more descriptive title, as this will become the commit message.

2025-03-08 00:12 UTC, corey-derochie-amd commented on src/transport/net_ib.cc
>  build_ib_list:
This whole block is removed in NCCL 2.24, so won't matter for long.

2025-03-08 00:18 UTC, corey-derochie-amd commented on src/transport/net_ib.cc
> +      if (ncclSuccess != wrap_ibv_free_device_list(devices)) { ret = ncclInternalError; goto fail;}
The original behaviour would avoid returning an error if there were no devices. To maintain that behaviour, you could do this.
```suggestion
      if ((ncclSuccess != wrap_ibv_free_device_list(devices)) && nIbDevs) { ret = ncclInternalError; goto fail; }
```

2025-03-08 00:19 UTC, corey-derochie-amd commented on src/transport/net_ib.cc
> +      if (ncclSuccess != wrap_ibv_free_device_list(devices)) { ret = ncclInternalError; goto fail;}
Doing so would also skip your `WARN` below, so you would have to decide whether that's necessary in that case.

2025-03-08 00:33 UTC, corey-derochie-amd approved these changes
LGTM, I've left a few suggestions to consider.

2025-03-08 00:35 UTC, PJAvinash commented on src/transport/net_ib.cc
> +      if (ncclSuccess != wrap_ibv_free_device_list(devices)) { ret = ncclInternalError; goto fail;}
Ideally we would like to detect if wrap_ibv_free_device_list() is failing/not behaving as expected for some reason ?

2025-03-10 14:55 UTC, corey-derochie-amd commented on src/transport/net_ib.cc
> +      if (ncclSuccess != wrap_ibv_free_device_list(devices)) { ret = ncclInternalError; goto fail;}
I'm honestly not sure if it matters for an empty list, but in general I agree we would like to know if this call is failing, as I think it should never fail.

2025-03-17 16:21 UTC, merged