Add ncclCommSplit test
ROCmSoftwarePlatform/rccl pull request #852
Opened 2023-08-16 19:22 UTC by BertanDogancay

2023-08-16 19:39 UTC, gilbertlee-amd requested changes

2023-08-16 19:39 UTC, gilbertlee-amd commented on test/SplitCommsTest.cpp
> +        NCCLCHECK(ncclGroupEnd());
Use ncclCommInitAll instead, to avoid all the resources required by ncclGetUniqueId

2023-08-16 19:39 UTC, gilbertlee-amd commented on test/SplitCommsTest.cpp
> +        NCCLCHECK(ncclCommCount(comms[i], &originalNRank));
What are these used for?

2023-08-16 19:39 UTC, gilbertlee-amd commented on test/SplitCommsTest.cpp
> +        ASSERT_LE(subCommNRank, maxExpectedSubCommNRank);
This math is wrong.
E.g.  If comms.size() == 5, and numSubComms = 3, then it expects 2,1,1.

2023-08-16 19:39 UTC, gilbertlee-amd commented on test/SplitCommsTest.cpp
> +        ASSERT_EQ(originalNRank, subCommNRank);
duplicate

2023-08-16 19:39 UTC, gilbertlee-amd commented on test/SplitCommsTest.cpp
> +        ASSERT_EQ(subCommNRank, numReducedRanks);
should check that the ranks >= numReducedRanks have NULL for new comm too

2023-08-16 19:39 UTC, gilbertlee-amd commented on test/SplitCommsTest.cpp
> +        ASSERT_LE(subCommNRank, maxExpectedSubCommNRank);
You can just increment a counter during ncclCommSplit based on the color, and track color of each rank and look it up instead of doing this math.

2023-08-16 21:47 UTC, gilbertlee-amd requested changes

2023-08-16 21:47 UTC, gilbertlee-amd commented on test/SplitCommsTest.cpp
> +        ASSERT_EQ(subCommNRank, mapCounter[subCommRank]);
This is still wrong.  mapCounter counts by color, not subCommRank.

2023-08-25 22:00 UTC, akolliasAMD approved these changes

2023-08-25 22:07 UTC, gilbertlee-amd approved these changes

2023-08-25 22:26 UTC, merged